// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using audexa_backend.Data;

#nullable disable

namespace audexa_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009052100_AddAudioConfiguration")]
    partial class AddAudioConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("audexa_backend.Models.AudioConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationOutputId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");
                    b.ToTable("AudioConfigurations");
                });

            modelBuilder.Entity("audexa_backend.Models.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");
                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<int>("SampleRate")
                        .HasColumnType("INTEGER");
                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");
                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("audexa_backend.Models.OutputMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");
                    b.Property<Guid>("AudioConfigurationId")
                        .HasColumnType("TEXT");
                    b.Property<string>("OutputId")
                        .IsRequired()
                        .HasColumnType("TEXT");
                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("AudioConfigurationId", "OutputId")
                        .IsUnique();
                    b.HasIndex("AudioConfigurationId", "RoomId")
                        .IsUnique();
                    b.ToTable("OutputMappings");
                });

            modelBuilder.Entity("audexa_backend.Models.OutputMapping", b =>
                {
                    b.HasOne("audexa_backend.Models.AudioConfiguration", "AudioConfiguration")
                        .WithMany("Mappings")
                        .HasForeignKey("AudioConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("AudioConfiguration");
                });

            modelBuilder.Entity("audexa_backend.Models.AudioConfiguration", b =>
                {
                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
